default_platform(:ios)

platform :ios do
  desc "Upload an ipa to App Store Connect (TestFlight)"
  lane :submit do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_filepath: ENV.fetch("ASC_KEY_PATH")
    )
    upload_to_testflight(
      api_key: api_key,
      ipa: options.fetch(:ipa),
      skip_waiting_for_build_processing: true
    )
  end
end

platform :android do
  desc "Upload an aab to Google Play"
  lane :submit do |options|
    upload_to_play_store(
      package_name: options.fetch(:package_name),
      aab: options.fetch(:aab),
      track: ENV.fetch("PLAY_TRACK", "internal"),
      json_key: ENV.fetch("PLAY_JSON_KEY"),
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
